import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-article',
  templateUrl: './article.component.html',
  styleUrls: ['./article.component.css']
})
export class ArticleComponent implements OnInit {

  @Input() item: Article = <Article>{};

  @Output() delete = new EventEmitter<number>();

  constructor() { }

  ngOnInit(): void {
  }

  btnDelete() {
    this.delete.emit(this.item.id);
  }

}

// Generated by https://quicktype.io

export interface Article {
  id:              number;
  href:            string;
  title:           string;
  date:            string;
  author:          string;
  category:        string;
  "category-link": string;
  summary:         string;
}


